Added "-listen" flag to AIR build params
openfl/lime pull request #1475
Opened 2021-08-30 18:51 UTC by Borman2000

Build AIR app with _-listen_ flag instead of _-connect_ to debug AIR app on device **over the usb** (default port 7936)

2021-11-18 00:26 UTC, player-03 commented
The first and third commits look fine at a glance, but 9f4f124 isn't a great way to do this.

- All projects have to keep track of `assetsFolders`, even though only AIR projects need it.
- Since you're passing a whole directory, AIR will ignore any asset filters (include/exclude) from project.xml.
- AIR doesn't know how to process Haxe templates, so any of those are present it may break the build.

I do see the reasoning here. Windows has a hard limit on command line length, and their [suggestions to work around it](https://docs.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/command-line-string-limitation) amount to "pass less data" and "store your data in a file for the program to read." Passing less data isn't a great option (as described above), so it would be nice to use the second option. But of course [AIR doesn't support it](https://help.adobe.com/en_US/air/build/WS901d38e593cd1bac1e63e3d128fc240122-7ff2.html).

How about this for a solution?

1. Collect the assets individually (instead of using `assetsFolders`).
2. Create a temporary folder. Call it `targetDirectory + "/assets"` or something.
3. Copy all non-embedded assets to this folder, one by one. So instead of `files.push(asset.targetPath)`, you run `AssetHelper.copyAsset(asset, targetDirectory + "/assets")`.
4. Now that the temporary folder has the correct assets, pass it to AIR: `files.push(targetDirectory + "/assets")`.

2022-12-29 23:51 UTC, player-03 requested changes

2022-12-29 23:51 UTC, player-03 commented on externs/air/sys/FileSystem.hx
> +	public static function readDirectory(path:String):Array<String> {return [];}
Not necessary. If this is causing errors, something is set up incorrectly on your end.

2022-12-29 23:51 UTC, player-03 commented on src/lime/tools/AIRHelper.hx
> +					args.push("-connect");
Should follow Lime's formatting conventions.

2022-12-29 23:51 UTC, player-03 commented on src/lime/tools/AIRHelper.hx
> +            }
This whole section should use tabs instead of spaces.

2022-12-29 23:51 UTC, player-03 commented on src/lime/tools/AIRHelper.hx
> +                if(hasARMV7 || project.architectures.length == 0){
This is redundant. `hasARMV7` was already defined as `ArrayTools.containsValue(project.architectures, Architecture.ARMV7) || project.architectures.length == 0`.

2022-12-29 23:51 UTC, player-03 commented on src/lime/tools/AIRHelper.hx
> +            System.runCommand(workingDirectory, project.defines.get("AIR_SDK") + "/bin/adt", args);
This line should use tabs.

2022-12-29 23:51 UTC, player-03 commented on src/lime/tools/AIRHelper.hx
> +//				["-uninstallApp"].concat(args).concat(["-appid", project.meta.packageName]), true, true);
This will need to be cleaned up. Either delete or create a compiler flag to toggle it.

2022-12-29 23:51 UTC, player-03 commented on src/lime/tools/AndroidHelper.hx
> +		return;
You can't just disable an AndroidHelper function because you want Air apps to function differently. Find the call to `uninstall()` and disable that.

2022-12-29 23:51 UTC, player-03 commented on src/lime/tools/HXProject.hx
> +	public var assetsFolders:Array<String>;
As I said in 2021, modifying `HXProject` isn't the way to do this. We'll need to revert all `HXProject` changes and try a different approach. [See my original comment for a detailed suggestion](https://github.com/openfl/lime/pull/1475#issuecomment-972369334).

2022-12-29 23:51 UTC, player-03 commented on tools/platforms/AIRPlatform.hx
> +					files.push(asset.targetPath);
Why create a new `if` block instead of changing the original?

2023-04-26 15:08 UTC, joshtynjala commented
Closing, since I added support for -listen in commit f8ec10b969d82946664a8fe6b719a8b776b574a7

2023-04-26 15:08 UTC, closed without merging